### ISSUE TITLE
No local device available on Safari

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [fully-forged/tune#141]
I tried to use tune on Safari 14.0.1 on macOS 11.01. Unfortunately it only displays error message that no devices are available. In console I only see this report:
```
{message: "Failed to initialize player"}
```

**Comment by cloud8421** [comment]
That's unfortunately a limitation of the Spotify Web Player SDK - playback requires specific compatibility to support DRM'ed content and Safari unfortunately doesn't have that (I use Safari myself) - see https://developer.spotify.com/documentation/web-playback-sdk/#supported-browsers.

I'm closing the issue as there's nothing I can do about it, sadly.
